print('Nudge nudge')
print('Wink wink')
print('Know what I mean?')
print("Don't fear!")
print("I'm here!")
print('Your assignment is to read "Hamlet" by tomorrow.')
print("""I'm reading "Hamlet" tonight.""")  
print("""One
Two
Three""")
name=input('What is your name')
print('Name',name)
name=input('What is your name')
print('Romal',name)
print("python's the best")
print('The cat said "meow"')
Height=input('What is your height')
print("Height",Height)
Color=input('what is your favorite color')
# print("Color",Color)
