Name=input('Name : ')
Address=input('Address : ')
City=input('City : ')
State=input('State : ')
ZIP=input('ZIP : ')
Telephone=input('Telephone Number : ')
print(" My Identity")
print("==========")
print('Name', Name)
print('address',Address)
print('City: ',City)
print('Sate: ',State)
print('Zip:',ZIP)
print("Phone:",Telephone)