Name=input('My Name  : ')
Address=input('Your current Address  : ')
City=input('Your Current City : ')
State=input('State : ')
Zip=input('Your current Zip Code : ')
Telephone=input('Your Telephone Number : ')
Major=input('Your College Major : ')
print('My Personla Information : ')
print('====^!!@@@@@@^^^========== ')
print('Name: ', Name)
print('Address: ', Address)
print('City: ', City)
print('State: ', State)
print('Zip: ', Zip)
print('Phone number: ', Telephone)
print('Major: ', Major)

